version: '3.2'

services:
      
  mysql: # Mysql container
    build:
      context: ./mysql
      dockerfile: Dockerfile
    container_name: Photon_Server-mysql
    image: mysql:5.7
    restart: always
    volumes:
      - ./mysql/my.cnf:/etc/mysql/my.cnf
      - ./mysql/init.sql:/docker-entrypoint-initdb.d/init.sql
    environment:
      MYSQL_ROOT_PASSWORD: rootPassword
      MYSQL_DATABASE: Photon_Server
      MYSQL_USER:     user
      MYSQL_PASSWORD: password
      TZ: Asia/Tokyo
    ports:
      - 3306:3306

  pma: # phpMyAdmin container
    container_name: Photon_Server-pma
    image: phpmyadmin/phpmyadmin:latest
    restart: always
    environment:
      PMA_USER: root
      PMA_PASSWORD: rootPassword
    ports:
      - 8080:80
    links:
      - mysql:db
